config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :admins, skip: [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  get '/categories/:id/edit(.:format)', to: 'categories#edit', as: 'edit_category'

  resources :categories, path: '', except: [:index] do
    resources :posts, path: '', except: [:index]
    get '/:friendly_id', to: 'posts#show', as: 'category_post'
  end

  root to: 'static_pages#index'
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :body, presence: true
  belongs_to :category

  before_validation :check_facebook_description
  before_save :calculate_reading_time

  private

  def calculate_reading_time
    image_comprehension_time = 0.5 * calculate_image_count
    reading_comprehension_time = calculate_word_count / 275
    self.reading_time = (image_comprehension_time + reading_comprehension_time).ceil
  end

  def calculate_word_count
    html_free_post = ActionView::Base.full_sanitizer.sanitize(body).squish
    html_free_post.scan(/[\w-]+/).size
  end

  def calculate_image_count
    # Find how many images are there in the post content
    body.scan(/<img([\w\W]+?)>/).size
  end

  def check_facebook_description
    self.facebook_description = meta_description if facebook_description.blank?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :auth_admin!, except: [:index, :show]
  before_action :set_category
  before_action :find_post, only: [:edit, :update, :show, :destroy]

  # Index action to render all posts
  def index
    redirect_to @category
  end

  # New action for creating post
  def new
    @post = @category.posts.build
  end

  # Create action saves the post into database
  def create
    @post = @category.posts.build(post_params)
    if @post.save
      flash[:notice] = 'Successfully created post!'
      redirect_to [@category, @post]
    else
      flash.now[:alert] = 'Error creating new post!'
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
    render layout: 'single_post'
  end

  # Update action updates the post with the new information
  def update
    if @post.update(post_params)
      flash[:notice] = 'Successfully updated post!'
      redirect_to [@category, @post]
    else
      flash[:alert] = 'Error updating post!'
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
    render layout: 'single_post'
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = 'Successfully deleted post!'
      redirect_to @category
    else
      flash[:alert] = 'Error updating post!'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :facebook_description, :meta_description)
  end

  def find_post
    @post = @category.posts.friendly.find(params[:id])
  end

  def set_category
    @category = Category.friendly.find(params[:category_id])
  end

  def auth_admin!
    set_category
    redirect_to @category, alert: "You aren't allowed to do that." unless admin_signed_in?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for([category, post]) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :facebook_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :meta_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'posts/form', category: @category, post: @post %>

app/views/posts/index.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
    <% @posts.each do |post| %>
    <div class="col-xs-12">
      <div class="text-center">
        <h2><%= post.title %></h2>
        <h6><%= post.created_at.strftime('%b %d, %Y') %></h6>
      </div>

      <div>
        <%= raw(post.body).truncate(358) %>
      </div>

      <div class="text-center">
        <%= link_to "READ MORE", post_path(post) %>
      </div>
      <br>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h2>Create New Post</h2>

<%= render 'posts/form', category: @category, post: @post %>

app/views/posts/show.html.erb
<% content_for :meta_description, @post.meta_description %>
<style type="text/css"><%= Pygments.css %></style>
<main class="container">
  <div class="row">
    <div class="col-xs-12 single-content">
      <p class="meta">
        <a class="" href="category.html">Mark Hoad</a> in <%= link_to @category.name, category_path(@category) %>
        <i class="link-spacer"></i> <i class="fa fa-bookmark"></i> <%= @post.reading_time %> minute read
      </p>
      <h1><%= @post.title %></h1>
      <p class="subtitle">Like I said, never told...</p>
      <%= markdown(@post.body) %>
      <% if admin_signed_in? %>
        <%= link_to 'Edit', [:edit, @category, @post], class: 'btn btn-default'%>
        <%= link_to "Delete", [@category, @post], class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
      <% end %>
    </div>  
  </div> <!--/row -->
</main> <!-- /container -->

<footer class="single">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-2">
        <%= image_tag("profile-1.jpg", class: "user-icon", alt: "post-image") %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="category-list">
          <p>
            Originally Published: <span><%= @post.created_at.strftime('%b %d, %Y') %></span><br>
            <% if(@post.created_at.strftime('%b %d, %Y') != @post.updated_at.strftime('%b %d, %Y')) %>
              Last Updated: <span><%= @post.updated_at.strftime('%b %d, %Y') %></span>
            <% end %>
          </p>
          <p><a href="#">Mark Hoad</a> in <%= link_to @category.name, category_path(@category) %></p>

          <div class="other-catergories">
            <h3>Also found in</h3>
            <ul>
                <li><a href="#">Stories</a>,</li>
                <li><a href="#">Life</a>,</li>
                <li><a href="#">Adventures</a></li>
            </ul>
          </div>
        </div>
      </div><!-- end col -->

      <div class="col-xs-12 col-sm-4">
        <div class="social">
          <p>Share this article</a>
          <div class="social-links">
            <a class="social-icon" href="#" data-platform="twitter" data-message="Message about this post" data-url="http://writertheme.com/post"><i class="fa fa-twitter"></i></a>
            <a class="social-icon" href="#" data-platform="facebook" data-message="Message about this post" data-url="http://writertheme.com/post"><i class="fa fa-facebook-official"></i></a>
            <a class="social-icon" data-platform="mail" href="mailto:support@writertheme.com"><i class="fa fa-envelope"></i></a>
          </div>
        </div>
      </div>
    </div><!-- end row -->
  </div>

  <div class="row read-another-section">
    <a href="post.html">
      <div class="col-sm-6 col-md-2 no-gutter read-another-container">
        <div class="overlay"></div>
        <%= image_tag("square-iceland.jpg", alt: "post-image") %>
        <h3 class="read-another">Land of Fire &amp; Ice</h3>
      </div>
    </a>
    <a href="post.html">
      <div class="col-sm-6 col-md-2 no-gutter read-another-container">
        <div class="overlay"></div>
        <%= image_tag("square-spain.jpg", alt: "post-image") %>
        <h3 class="read-another">The Coast of Your Mind</h3>
      </div>
    </a>
    <a href="post.html">
      <div class="col-sm-6 col-md-2 no-gutter read-another-container">
        <div class="overlay"></div>
        <%= image_tag("square-peak.jpg", alt: "post-image") %>
        <h3 class="read-another">Get Out of Your Comfort Zone</h3>
      </div>
    </a>
    <a href="post.html">
      <div class="col-sm-6 col-md-2 no-gutter read-another-container">
        <div class="overlay"></div>
        <%= image_tag("square-woods.jpg", alt: "post-image") %>
        <h3 class="read-another">Not All Who Wander Are Lost</h3>
      </div>
    </a>
    <a href="post.html">
      <div class="col-sm-6 col-md-2 no-gutter read-another-container">
        <div class="overlay"></div>
        <%= image_tag("square-sunset.jpg", alt: "post-image") %>
        <h3 class="read-another">Open Your Mind</h3>
      </div>
    </a>
    <a href="post.html">
      <div class="col-sm-6 col-md-2 no-gutter read-another-container">
        <div class="overlay"></div>
        <%= image_tag("square-mountain.jpg", alt: "post-image") %>
        <h3 class="read-another">Ten Reasons to Hike</h3>
      </div>
    </a>
  </div>
</footer>