config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :admins, skip: [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  get '/categories/:id/edit(.:format)', to: 'categories#edit', as: 'edit_category'

  resources :categories, path: '', except: [:index] do
    resources :posts, path: '', except: [:index]
    get '/:friendly_id', to: 'posts#show', as: 'category_post'
  end

  root to: 'static_pages#index'
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true
  validates :description, presence: true
  has_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:edit, :update, :show, :destroy]
  before_action :auth_admin!, except: [:index, :show]

  # Index action to render all categories
  def index
    @categories = Category.all
  end

  # New action for creating a category
  def new
    @category = Category.new
    render layout: 'single_post'
  end

  # Create action saves the category into database
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Successfully created category!'
      redirect_to category_path(@category)
    else
      flash[:alert] = 'Error creating new category!'
      render :new
    end
  end

  # Edit action retrives the category and renders the edit page
  def edit
    render layout: 'single_post'
  end

  # Update action updates the category with the new information
  def update
    if @category.update_attributes(category_params)
      flash[:notice] = 'Successfully updated category!'
      redirect_to category_path(@category)
    else
      flash[:alert] = 'Error updating category!'
      render :edit
    end
  end

  # The show action renders the individual category after retrieving the the id
  def show
  end

  # The destroy action removes the category permanently from the database
  def destroy
    if @category.destroy
      flash[:notice] = 'Successfully deleted category!'
      redirect_to categories_path
    else
      flash[:alert] = 'Error updating category!'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def find_category
    @category = Category.friendly.find(params[:id])
  end

  def auth_admin!
    redirect_to root_path, alert: "You aren't allowed to do that." unless admin_signed_in?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:" %>
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= render "categories/form" %>

app/views/categories/index.html.erb
<% content_for :sidebar_title, "Categories" %>
<% content_for :sidebar_description, "I tend to blog about a bunch of different topics so 
                                      this is the place to check out specific categories" %>

<section class="col-md-6 col-sm-12 col-md-offset-6 alt-main">
  <div class="sub-nav">
      <a href="#" >Categories</a>
      <% if admin_signed_in? %>
        <%= link_to 'Create Category', new_category_path %>
      <% end %>
  </div>

  <div class="home-page-categories animated fadeIn ">
    <div class="category row">
      <section>
        <% @categories.each do |category| %>
          <div class="category-preview col-xs-6 col-sm-4 ">
          <h2><%= category.name %></h2>
          <%= link_to category_path(category) do %>
            <%= image_tag("cover-2.jpg", alt: category.name) %>
          <% end %>
          </div>
        <% end %>
      </section>
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<h2>Create New Category</h2>

<%= render "categories/form" %>

app/views/categories/show.html.erb
<% content_for :sidebar_title, @category.name %>
<% content_for :sidebar_description, @category.description %>

<section class="col-md-7 col-sm-12 col-md-offset-5 main-content">
  <div class="sub-nav">
    <a href="#" class="select-posts active">Posts</a>
    <% if admin_signed_in? %>
      <%= link_to 'New Post', new_category_post_path(@category) %>
      <%= link_to 'Edit Category', edit_category_path(@category) %>
      <%= link_to 'Delete Category', category_path(@category), :method => :delete %>
    <% end %>
  </div>

  <div class="home-page-posts animated fadeIn ">
    <% @category.posts.each do |post| %>
      <article class="post">
        <div class="post-preview col-xs-10  no-gutter">
          <h2><%= link_to post.title, [@category, post] %></a></h2>
          <p>It was a cold December morning, as I sat out on my porch I decided today was the day. </p>
          <p class="meta">
            Last Updated: <%= post.updated_at.strftime('%b %d, %Y') %> 
            <i class="link-spacer"></i> 
            <i class="fa fa-bookmark"></i> <%= post.reading_time %> minute read
          </p>
        </div>
        <div class=" col-xs-2  no-gutter">
          <%= image_tag("profile-1.jpg", class: "user-icon", alt: "user-image")%>
        </div>
      </article>
    <% end %>
  </div>
</section>