config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :admins, skip: [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  get '/categories/:id/edit(.:format)', to: 'categories#edit', as: 'edit_category'

  resources :categories, path: '', except: [:index] do
    resources :posts, path: '', except: [:index]
    get '/:friendly_id', to: 'posts#show', as: 'category_post'
  end

  root to: 'static_pages#index'
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= key %>alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_js_main_nav.html.erb
<nav id="menu-target">
    <ul>
        <li><i class="fa fa-home"></i><%= link_to "Home", root_path %></li>
        <li><i class="fa fa-user"></i><a href="#">John Smith</a></li>
        <li><i class="fa fa-anchor"></i><a href="#">About</a></li>
        <li><i class="fa fa-star"></i><a href="#">Favorites</a></li>
        <li><i class="fa fa-paper-plane"></i><a href="#">Contact</a></li>
    </ul>
    <hr>
    <ul>
        <li><i class="fa fa-file"></i><a href="#">Post Page</a></li>
        <li><i class="fa fa-file"></i><a href="#">Post with Sidebar</a></li>

        <li><i class="fa fa-home"></i><a href="#">Alternate Home</a></li>
        <li><i class="fa fa-image"></i><a href="#">Category Page</a></li>
        <% if admin_signed_in? %>
        <!--This block is only visible to signed in admins -->
          <li><%= link_to 'My Account', edit_admin_registration_path  %></li>
          <li><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></li>
        <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', new_admin_session_path  %></li>
        <% end %>
    </ul>
</nav>

app/views/layouts/_nojs_main_nav.html.erb
<!-- if the user has javascript disabled they can still use the menu -->
<noscript>
    <nav class="no-js-menu">
        <ul>
            <li><i class="fa fa-home"></i><%= link_to "Home", root_path %></li>
            <li><i class="fa fa-user"></i><a href="#">John Smith</a></li>
            <li><i class="fa fa-anchor"></i><a href="#">About</a></li>
            <li><i class="fa fa-star"></i><a href="#">Favorites</a></li>
            <li><i class="fa fa-paper-plane"></i><a href="#">Contact</a></li>
            <li><i class="fa fa-file"></i><a href="#">Post Page</a></li>
            <li><i class="fa fa-file"></i><a href="#">Post with Sidebar</a></li>
            <li><i class="fa fa-home"></i><a href="#">Alternate Home</a></li>
            <li><i class="fa fa-image"></i><a href="#">Category Page</a></li>
        </ul>
    </nav>
</noscript>
<!-- end no script -->

app/views/layouts/_sidebar.html.erb
<%= render "layouts/js_main_nav" %>

<section class="sidebar col-md-5 col-sm-12" style="background-image: url(<%= path_to_image("default-sidebar.jpg")%>">

    <span class="menu-trigger animated fadeInDown">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </span>

    <%= render "layouts/site_info" %>
</section><!-- end sidebar -->

app/views/layouts/_site_info.html.erb
<div class="site-info">
  <div class="primary-info">
    <% if content_for? :sidebar_title %>
      <h1><%= yield :sidebar_title %></h1>
    <% end %>
    <% if content_for? :sidebar_description %>
      <p><%= yield :sidebar_description %></p>
    <% end %>

    <p><strong>Current Location:</strong> Manchester, UK</p>
    </div>
    <div class="secondary-info">
        <p>
            <a class="btn btn-primary" href="#"><i class="fa fa-user-plus"></i>Get notified of new posts</a>
        </p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Personal Blog</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
        <%= javascript_include_tag "html5shiv.min.js" %>
    <![endif]-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash_messages" %>
    <%= render "layouts/nojs_main_nav" %>
    <main class="container left-container">
      <div class="row">
        <%= render "layouts/sidebar" %>
        <%= yield %>
      </div> <!--/row -->
    </main> <!-- /container -->
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Personal Blog</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'devise', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash_messages" %>
      <%= yield %>
  </body>
</html>

app/views/layouts/single_post.html.erb
<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <title>Personal Blog Single Post</title>
    <% if content_for? :meta_description %>
      <meta name="description" content="<%= yield :meta_description %>">
    <% end %>
    <% if content_for? :facebook_description %>
      <meta name="description" content="<%= yield :facebook_description %>">
    <% end %>
    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
        <%= javascript_include_tag "html5shiv.min.js" %>
    <![endif]-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash_messages" %>
    <%= render "layouts/nojs_main_nav" %>

    <header class="hero-image" role="banner" style="background-image: url(<%= path_to_image("default-single-hero.jpg")%>);">
      <span class="menu-trigger animated fadeInDown">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
      </span>
      <%= render "layouts/js_main_nav" %>
    </header>

    <%= yield %>
    
  </body>
</html>